services:
  - type: web
    name: taskflow-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn taskflow.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: taskflow.settings
      - key: PYTHON_VERSION
        value: 3.11
